## Numpy

In [1]:
import numpy as np

1. Create an `ndarray` of shape (3,5). All values of the array are 100.

In [4]:
x = np.full((3,5), 100)
x

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

2. Create a border of zeros that surround the result in Question 1, so that the output is of shape (5,7), the outside values are 0 and the inside values are 100. 

In [7]:
np.r_[np.zeros(7)[None, :], np.c_[np.zeros(3), x, np.zeros(3)], np.zeros(7)[None, :]]

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0., 100., 100., 100., 100., 100.,   0.],
       [  0., 100., 100., 100., 100., 100.,   0.],
       [  0., 100., 100., 100., 100., 100.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.]])

3. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.


In [11]:
y = np.full((5,5), np.nan)
for i in range(1, 5):
    y[i, i-1] = i
y

array([[nan, nan, nan, nan, nan],
       [ 1., nan, nan, nan, nan],
       [nan,  2., nan, nan, nan],
       [nan, nan,  3., nan, nan],
       [nan, nan, nan,  4., nan]])

4. Create a checkerboard 8x8 matrix using the tile function

In [13]:
np.tile(np.array([[0,1],[1,0]]), [4,4])

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

5. Sort a 2d-array by the nth column

In [25]:
z = np.random.randn(20).reshape(5,4)
n = 3
z[z[:,n].argsort()]

array([[-0.91751631,  0.72190701,  0.86097107, -0.42763368],
       [ 1.11420173,  0.3604468 ,  0.58159724,  0.078948  ],
       [-0.67250232, -0.13715218, -0.38528353,  0.55603961],
       [ 0.74827186,  0.17953217,  0.40380985,  0.60538424],
       [-0.55802345, -1.37311397,  0.06605564,  0.79463854]])

6. Compute a matrix rank

In [29]:
np.linalg.matrix_rank(z)

4

In [31]:
np.linalg.matrix_rank(x)

1

7. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [35]:
# method 1:
np.random.randn(5*5*3).reshape(5,5,3) * np.random.randn(5*5).reshape(5,5)[:,:,None]

array([[[-3.36095587e-01,  1.62436409e-01, -2.97358116e-03],
        [ 1.10379012e-01, -3.15315005e-01,  8.70597313e-01],
        [ 5.15448335e-01, -1.06115540e-01,  1.52423201e+00],
        [ 9.52454938e-02, -5.19282702e-01,  5.53052164e-01],
        [-2.42057035e-02, -1.13835079e-01, -1.79375194e-03]],

       [[ 2.93445028e-01, -9.87423181e-01,  7.73969939e-01],
        [ 2.16316726e-01, -6.36525981e-02,  1.22258309e-01],
        [-3.73934985e-01, -1.67599643e+00,  9.70565602e-01],
        [ 5.95419389e-01, -3.42641315e-01,  3.37541706e-01],
        [-1.49350184e+00, -2.49143860e+00,  4.80635642e-01]],

       [[ 5.51578683e-01, -8.79744769e-02,  1.08897887e-01],
        [ 7.05310458e-01,  1.08934480e+00, -1.77489047e-01],
        [-1.83363726e-01, -9.49325086e-01,  5.65468754e-01],
        [-3.00892316e-01, -9.05857349e-03,  2.43761894e+00],
        [-4.83198892e-01,  4.54049974e-01, -4.99007430e-01]],

       [[ 3.16514130e-01,  2.71409098e-01, -3.51167916e-01],
        [ 2.372011

In [36]:
# method 2:
np.random.randn(5*5*3).reshape(5,5,3) * np.random.randn(5*5).reshape(5,5)[:,:,np.newaxis]

array([[[ 4.93750012e-01,  1.32883794e-01,  1.09912005e-01],
        [ 6.63034019e-01,  7.31851931e-01,  5.18748739e-01],
        [-2.37477527e-01, -4.54486148e-01, -1.17968071e+00],
        [-1.04121898e-01, -3.90686396e-01, -3.86339408e-01],
        [-4.12534270e-01, -1.28855566e-01, -4.99356932e-01]],

       [[ 8.85568406e-03,  1.95609570e-02, -1.79448470e-02],
        [ 1.05975806e+00,  6.87137221e-02, -7.48605724e-01],
        [-6.96587148e-01,  1.03262873e+00,  6.43596305e-01],
        [-1.01706777e+00, -5.17384131e-01,  4.13051668e-01],
        [ 7.05448007e-02,  4.45989885e-03,  2.90873001e-02]],

       [[-1.81836864e+00, -1.10140653e+00,  1.12383999e+00],
        [-4.93540324e-01,  1.38523910e-01,  1.20984461e-01],
        [ 3.67337077e+00, -5.84378636e-01,  1.12903761e+00],
        [ 2.43014115e-04, -3.83481963e-02, -2.18214702e-02],
        [-8.63719054e-02,  1.73235115e-02, -7.67140964e-02]],

       [[ 3.96256538e-01,  5.33636825e-01,  3.77145326e-02],
        [-2.849498

In [37]:
# method 3:
np.random.randn(5*5*3).reshape(5,5,3) * np.random.randn(5*5).reshape(5,5).reshape(5,5,-1)

array([[[ 1.39227090e+00, -9.24131331e-01, -8.78108157e-01],
        [ 8.31171197e-03,  1.05308327e-02, -6.21971792e-02],
        [-1.86837137e+00,  4.15898419e-01,  2.06498671e-01],
        [-8.58976468e-01,  3.45563526e-01, -5.77909647e-01],
        [-8.31387038e-02, -4.38560868e-02, -4.97209538e-02]],

       [[ 2.82273851e-01, -5.83656122e-01, -1.09592484e+00],
        [ 2.08755821e+00,  9.61627738e-01, -2.29530000e+00],
        [ 1.34440970e+00,  1.41082956e-01,  3.71984355e-01],
        [-8.67967161e-01, -2.20097375e-01, -3.19293019e-01],
        [ 2.06353704e+00, -2.35184918e+00,  1.65483269e+00]],

       [[-2.55521368e+00, -1.08832133e+00, -5.75946263e-01],
        [-9.84538065e-01,  5.53415629e-01,  1.79566901e-01],
        [ 4.55136569e-01, -6.44180077e-01,  1.68690085e+00],
        [ 2.40326528e-01,  2.22817281e+00, -7.79906777e-02],
        [-5.23792653e-01, -5.94926450e-01,  4.43892249e-01]],

       [[-2.52280183e+00,  2.48759066e-01, -3.60227038e+00],
        [ 1.512496

8. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [51]:
xx = np.arange(256).reshape(16,16)
xx

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15],
       [ 16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
         29,  30,  31],
       [ 32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,
         45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,
         61,  62,  63],
       [ 64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
        109, 110, 111],
       [112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124,
        125, 126, 127],
       [128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159],
       [160, 161, 162, 163, 16

In [66]:
# method 1: use reshape
xx.reshape(16, 4, 4).sum(axis=-1).reshape(4, 4, 4).sum(axis=-2)

array([[ 408,  472,  536,  600],
       [1432, 1496, 1560, 1624],
       [2456, 2520, 2584, 2648],
       [3480, 3544, 3608, 3672]])

In [120]:
# method 2: use reduceat
np.add.reduceat(
    np.add.reduceat(xx, np.arange(0,16,4), axis=1),
    np.arange(0,16,4))

array([[ 408,  472,  536,  600],
       [1432, 1496, 1560, 1624],
       [2456, 2520, 2584, 2648],
       [3480, 3544, 3608, 3672]])

9. Get the n largest values of an array

In [176]:
def game_of_life(arr):
    # deal with the boundary cells:
    # consider the left and right edges of the field to be stitched together, and the top and bottom edges also, yielding a toroidal array
    # left cell
    left = np.c_[arr[:, -1:], arr[:, :-1]]
    # right cell
    right = np.c_[arr[:, 1:], arr[:, 0:1]]
    # upper cell
    upper = np.r_[arr[-1:, :], arr[:-1, :]]
    # lower cell
    lower = np.r_[arr[1:, :], arr[0:1, :]]
    # upper-left cell
    upperleft = np.r_[np.c_[arr[-1,-1], arr[-1:, :-1]], np.c_[arr[:-1, -1:], arr[:-1, :-1]]]
    # upper-right cell
    upperright = np.r_[np.c_[arr[-1:, 1:], arr[-1,0]], np.c_[ arr[:-1, 1:], arr[:-1, :1],]]
    # lower-right cell
    lowerright = np.r_[np.c_[arr[1:, 1:], arr[1:, :1]], np.c_[arr[:1, 1:], arr[0,0]]]
    # lower-left cell
    lowerleft = np.r_[np.c_[arr[1:, -1:], arr[1:, :-1]], np.c_[arr[0,-1], arr[:1, :-1]]]
    sums = left+right+upper+lower+upperleft+upperright+lowerright+lowerleft
    # conditions
    #     Any live cell with two or three live neighbours survives.
    #     Any dead cell with three live neighbours becomes a live cell.
    #     All other live cells die in the next generation. Similarly, all other dead cells stay dead.
    res = np.where(((sums == 3) & (arr == 0)) | (((sums == 2) | (sums == 3)) & (arr == 1)), 1, 0)
    return res

In [179]:
# Test cases
# 1. Still - Block
arr0 = np.array([[0,0,0,0],
                 [0,1,1,0],
                 [0,1,1,0],
                 [0,0,0,0]])
np.allclose(game_of_life(arr0), arr0)

True

In [ ]:
# 2. Still - Tub
arr1 = np.array([[0,0,0,0,0],
                 [0,0,1,0,0],
                 [0,1,0,1,0],
                 [0,0,1,0,0],
                 [0,0,0,0,0]])
np.allclose(game_of_life(arr1), arr1)

In [183]:
# 3. Oscillators - Blinker
arr21 = np.array([[0,0,0,0,0],
                 [0,0,1,0,0],
                 [0,0,1,0,0],
                 [0,0,1,0,0],
                 [0,0,0,0,0]])
arr22 = np.array([[0,0,0,0,0],
                 [0,0,0,0,0],
                 [0,1,1,1,0],
                 [0,0,0,0,0],
                 [0,0,0,0,0]])

np.allclose(game_of_life(arr21), arr22), np.allclose(game_of_life(arr22), arr21)

(True, True)

In [184]:
# 4. Oscillators - Beacon
arr31 = np.array([[0,0,0,0,0,0],
                  [0,1,1,0,0,0],
                  [0,1,1,0,0,0],
                  [0,0,0,1,1,0],
                  [0,0,0,1,1,0],
                  [0,0,0,0,0,0]])
arr32 = np.array([[0,0,0,0,0,0],
                  [0,1,1,0,0,0],
                  [0,1,0,0,0,0],
                  [0,0,0,0,1,0],
                  [0,0,0,1,1,0],
                  [0,0,0,0,0,0]])

np.allclose(game_of_life(arr31), arr32), np.allclose(game_of_life(arr32), arr31)

(True, True)

Check https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb for more Numpy exercises.

## Pandas

In [79]:
import pandas as pd
import seaborn as sb

1. Using NumPy, create a Pandas DataFrame with five rows and three columns

In [80]:
pd.DataFrame(np.arange(15).reshape(5,3))

0   1   2
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14

The following six questions depend on the penguins dataset.

In [81]:
df_penguins = sb.load_dataset('penguins')

In [84]:
df_penguins.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [83]:
df_penguins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


2. What function can we use to drop the rows that have missing data?

In [93]:
df_full = df_penguins.dropna(axis=0)

3. By default, will the function in Question 2 modify df_penguins or will it return a copy?

return a copy

4. Let df_full be the dataframe obtained from dropping rows with missing data. What is the average bill length of a penguin, in millimeters, in this (df_full) data set?

In [94]:
df_full.bill_length_mm.mean()

43.992792792792805

5. Which species has the longest flippers?

In [96]:
df_full.groupby('species').flipper_length_mm.describe()

count        mean       std    min    25%    50%    75%    max
species                                                                  
Adelie     146.0  190.102740  6.521825  172.0  186.0  190.0  195.0  210.0
Chinstrap   68.0  195.823529  7.131894  178.0  191.0  196.0  201.0  212.0
Gentoo     119.0  217.235294  6.585431  203.0  212.0  216.0  221.5  231.0

Measured by group mean, max, min and median, Gentoo has the longest flippers.

6. Which two species have the most similar mean weight?

In [99]:
df_full.groupby('species').body_mass_g.mean().diff()

species
Adelie               NaN
Chinstrap      26.923852
Gentoo       1359.348739
Name: body_mass_g, dtype: float64

Chinstrap and Adelie have the most similar mean weight.

7. How could you sort by species first, then by body mass?

In [100]:
df_full.sort_values(['species', 'body_mass_g'])

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
58   Adelie     Biscoe            36.5           16.6              181.0   
64   Adelie     Biscoe            36.4           17.1              184.0   
54   Adelie     Biscoe            34.5           18.1              187.0   
98   Adelie      Dream            33.1           16.1              178.0   
116  Adelie  Torgersen            38.6           17.0              188.0   
..      ...        ...             ...            ...                ...   
331  Gentoo     Biscoe            49.8           15.9              229.0   
297  Gentoo     Biscoe            51.1           16.3              220.0   
337  Gentoo     Biscoe            48.8           16.2              222.0   
253  Gentoo     Biscoe            59.6           17.0              230.0   
237  Gentoo     Biscoe            49.2           15.2              221.0   

     body_mass_g     sex  
58        2850.0  Female  
64        2850.0  Female  
54        2900.0  Female  
98        2900.0  Female  
116       2900.0  Female  
..           ...     ...  
331       5950.0    Male  
297       6000.0    Male  
337       6000.0    Male  
253       6050.0    Male  
237       6300.0    Male  

[333 rows x 7 columns]

The following three questions depend on the taxis dataset.

In [101]:
df_taxis = sb.load_dataset('taxis')

In [102]:
df_taxis.head()

pickup              dropoff  passengers  distance  fare   tip  \
0  2019-03-23 20:21:09  2019-03-23 20:27:24           1      1.60   7.0  2.15   
1  2019-03-04 16:11:55  2019-03-04 16:19:00           1      0.79   5.0  0.00   
2  2019-03-27 17:53:01  2019-03-27 18:00:25           1      1.37   7.5  2.36   
3  2019-03-10 01:23:59  2019-03-10 01:49:51           1      7.70  27.0  6.15   
4  2019-03-30 13:27:42  2019-03-30 13:37:14           3      2.16   9.0  1.10   

   tolls  total   color      payment            pickup_zone  \
0    0.0  12.95  yellow  credit card        Lenox Hill West   
1    0.0   9.30  yellow         cash  Upper West Side South   
2    0.0  14.16  yellow  credit card          Alphabet City   
3    0.0  36.95  yellow  credit card              Hudson Sq   
4    0.0  13.40  yellow  credit card           Midtown East   

            dropoff_zone pickup_borough dropoff_borough  
0    UN/Turtle Bay South      Manhattan       Manhattan  
1  Upper West Side South      Manhattan       Manhattan  
2           West Village      Manhattan       Manhattan  
3         Yorkville West      Manhattan       Manhattan  
4         Yorkville West      Manhattan       Manhattan

In [103]:
df_taxis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   pickup           6433 non-null   object 
 1   dropoff          6433 non-null   object 
 2   passengers       6433 non-null   int64  
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object 
 9   payment          6389 non-null   object 
 10  pickup_zone      6407 non-null   object 
 11  dropoff_zone     6388 non-null   object 
 12  pickup_borough   6407 non-null   object 
 13  dropoff_borough  6388 non-null   object 
dtypes: float64(5), int64(1), object(8)
memory usage: 703.7+ KB


8. The 'pickup' column contains the date and time the customer picked up, but it's a string.  Add a column to the DataFrame, 'pickup_time', containing the value in 'pickup' as a DateTime.

In [104]:
df_taxis['pickup_time'] = pd.to_datetime(df_taxis['pickup'])

9. Create a subset of the dataframe to create a new DataFrame, taxis_one_day. This new DataFrame should have pickup_time values between '2019-03-23 00:06:00' (inclusive) and '2019-03-24 00:00:00' (exlusive).

In [107]:
taxis_one_day = df_taxis.query("pickup_time >= '2019-03-23 00:06:00' and pickup_time < '2019-03-24 00:00:00'")

In [110]:
taxis_one_day

pickup              dropoff  passengers  distance  fare  \
0     2019-03-23 20:21:09  2019-03-23 20:27:24           1      1.60   7.0   
8     2019-03-23 11:48:50  2019-03-23 12:06:14           1      3.63  15.0   
17    2019-03-23 20:50:49  2019-03-23 21:02:07           1      2.60  10.5   
117   2019-03-23 09:39:25  2019-03-23 09:56:45           0      3.60  15.5   
144   2019-03-23 18:35:01  2019-03-23 18:47:39           1      3.20  12.5   
...                   ...                  ...         ...       ...   ...   
6325  2019-03-23 20:52:40  2019-03-23 21:10:12           1      3.62  14.5   
6331  2019-03-23 11:27:00  2019-03-23 12:20:11           1      7.67  28.0   
6338  2019-03-23 18:05:38  2019-03-23 18:25:36           1      2.82  14.0   
6427  2019-03-23 18:26:09  2019-03-23 18:49:12           1      7.07  20.0   
6430  2019-03-23 22:55:18  2019-03-23 23:14:25           1      4.14  16.0   

       tip  tolls  total   color      payment                     pickup_zone  \
0     2.15    0.0  12.95  yellow  credit card                 Lenox Hill West   
8     1.00    0.0  19.30  yellow  credit card               East Harlem South   
17    2.00    0.0  16.30  yellow  credit card                  Midtown Center   
117   3.75    0.0  22.55  yellow  credit card                  Yorkville East   
144   2.00    0.0  17.80  yellow  credit card             UN/Turtle Bay South   
...    ...    ...    ...     ...          ...                             ...   
6325  0.00    0.0  15.80   green         cash  Long Island City/Hunters Point   
6331  0.00    0.0  28.00   green         cash                 Jackson Heights   
6338  0.00    0.0  14.80   green  credit card              Claremont/Bathgate   
6427  0.00    0.0  20.00   green         cash                     Parkchester   
6430  0.00    0.0  17.30   green         cash             Crown Heights North   

                      dropoff_zone pickup_borough dropoff_borough  \
0              UN/Turtle Bay South      Manhattan       Manhattan   
8                   Midtown Center      Manhattan       Manhattan   
17               East Harlem South      Manhattan       Manhattan   
117   Penn Station/Madison Sq West      Manhattan       Manhattan   
144                   East Village      Manhattan       Manhattan   
...                            ...            ...             ...   
6325                      Steinway         Queens          Queens   
6331                       Maspeth         Queens          Queens   
6338    Spuyten Duyvil/Kingsbridge          Bronx           Bronx   
6427             East Harlem South          Bronx       Manhattan   
6430                Bushwick North       Brooklyn        Brooklyn   

             pickup_time  
0    2019-03-23 20:21:09  
8    2019-03-23 11:48:50  
17   2019-03-23 20:50:49  
117  2019-03-23 09:39:25  
144  2019-03-23 18:35:01  
...                  ...  
6325 2019-03-23 20:52:40  
6331 2019-03-23 11:27:00  
6338 2019-03-23 18:05:38  
6427 2019-03-23 18:26:09  
6430 2019-03-23 22:55:18  

[209 rows x 15 columns]

10. From the dataframe in Question 9, take the mean of the numeric columns, grouped at one hour intervals.  Save the result as df_means, and display it.

In [118]:
# method 1:
taxis_one_day.groupby(pd.Grouper(key='pickup_time', freq='60Min')).mean()

passengers  distance       fare       tip     tolls  \
pickup_time                                                                
2019-03-23 00:00:00    1.000000  1.911667   8.583333  1.415000  0.000000   
2019-03-23 01:00:00    1.250000  1.325000   7.875000  1.525000  0.000000   
2019-03-23 02:00:00    1.727273  1.739091   8.181818  1.641818  0.000000   
2019-03-23 03:00:00    1.500000  3.377500  11.750000  2.410000  0.000000   
2019-03-23 04:00:00    2.000000  0.950000   5.500000  0.915000  0.000000   
2019-03-23 05:00:00    2.000000  1.270000   6.000000  0.980000  0.000000   
2019-03-23 06:00:00    1.000000  0.400000  21.500000  0.000000  0.000000   
2019-03-23 07:00:00    2.333333  0.980000   5.250000  1.165000  0.000000   
2019-03-23 08:00:00    1.000000  0.020000   2.500000  0.000000  0.000000   
2019-03-23 09:00:00    1.500000  1.352000   7.400000  1.674000  0.000000   
2019-03-23 10:00:00    1.000000  1.760000   8.750000  0.727500  0.000000   
2019-03-23 11:00:00    1.909091  2.070000  11.090909  0.803636  0.000000   
2019-03-23 12:00:00    2.000000  2.267143  10.260000  0.645714  0.000000   
2019-03-23 13:00:00    2.500000  1.167000   7.550000  2.074000  0.000000   
2019-03-23 14:00:00    2.470588  4.752941  18.330000  1.945294  1.003529   
2019-03-23 15:00:00    1.000000  6.557143  22.214286  3.210000  1.645714   
2019-03-23 16:00:00    2.000000  2.194545  10.454545  1.109091  0.000000   
2019-03-23 17:00:00    1.090909  1.913636  14.818182  2.688182  0.523636   
2019-03-23 18:00:00    1.571429  3.206429  12.821429  0.844286  0.411429   
2019-03-23 19:00:00    1.526316  2.097895  10.263158  1.176316  0.000000   
2019-03-23 20:00:00    1.400000  2.448000  11.100000  1.544000  0.000000   
2019-03-23 21:00:00    1.000000  2.017143  10.571429  1.420000  0.000000   
2019-03-23 22:00:00    1.307692  1.881538   8.923077  1.094615  0.000000   
2019-03-23 23:00:00    1.615385  3.725385  15.115385  1.696154  0.000000   

                         total  
pickup_time                     
2019-03-23 00:00:00  12.965000  
2019-03-23 01:00:00  12.575000  
2019-03-23 02:00:00  13.169091  
2019-03-23 03:00:00  17.335000  
2019-03-23 04:00:00  10.215000  
2019-03-23 05:00:00  10.530000  
2019-03-23 06:00:00  23.133333  
2019-03-23 07:00:00   9.298333  
2019-03-23 08:00:00   3.300000  
2019-03-23 09:00:00  12.124000  
2019-03-23 10:00:00  12.152500  
2019-03-23 11:00:00  14.667273  
2019-03-23 12:00:00  13.420000  
2019-03-23 13:00:00  12.344000  
2019-03-23 14:00:00  24.267059  
2019-03-23 15:00:00  30.370000  
2019-03-23 16:00:00  14.431818  
2019-03-23 17:00:00  20.739091  
2019-03-23 18:00:00  16.427143  
2019-03-23 19:00:00  14.226316  
2019-03-23 20:00:00  15.944000  
2019-03-23 21:00:00  15.791429  
2019-03-23 22:00:00  13.433077  
2019-03-23 23:00:00  20.034615

In [114]:
# method 2:
taxis_one_day.set_index('pickup_time').resample('60min').mean()

passengers  distance       fare       tip     tolls  \
pickup_time                                                                
2019-03-23 00:00:00    1.000000  1.911667   8.583333  1.415000  0.000000   
2019-03-23 01:00:00    1.250000  1.325000   7.875000  1.525000  0.000000   
2019-03-23 02:00:00    1.727273  1.739091   8.181818  1.641818  0.000000   
2019-03-23 03:00:00    1.500000  3.377500  11.750000  2.410000  0.000000   
2019-03-23 04:00:00    2.000000  0.950000   5.500000  0.915000  0.000000   
2019-03-23 05:00:00    2.000000  1.270000   6.000000  0.980000  0.000000   
2019-03-23 06:00:00    1.000000  0.400000  21.500000  0.000000  0.000000   
2019-03-23 07:00:00    2.333333  0.980000   5.250000  1.165000  0.000000   
2019-03-23 08:00:00    1.000000  0.020000   2.500000  0.000000  0.000000   
2019-03-23 09:00:00    1.500000  1.352000   7.400000  1.674000  0.000000   
2019-03-23 10:00:00    1.000000  1.760000   8.750000  0.727500  0.000000   
2019-03-23 11:00:00    1.909091  2.070000  11.090909  0.803636  0.000000   
2019-03-23 12:00:00    2.000000  2.267143  10.260000  0.645714  0.000000   
2019-03-23 13:00:00    2.500000  1.167000   7.550000  2.074000  0.000000   
2019-03-23 14:00:00    2.470588  4.752941  18.330000  1.945294  1.003529   
2019-03-23 15:00:00    1.000000  6.557143  22.214286  3.210000  1.645714   
2019-03-23 16:00:00    2.000000  2.194545  10.454545  1.109091  0.000000   
2019-03-23 17:00:00    1.090909  1.913636  14.818182  2.688182  0.523636   
2019-03-23 18:00:00    1.571429  3.206429  12.821429  0.844286  0.411429   
2019-03-23 19:00:00    1.526316  2.097895  10.263158  1.176316  0.000000   
2019-03-23 20:00:00    1.400000  2.448000  11.100000  1.544000  0.000000   
2019-03-23 21:00:00    1.000000  2.017143  10.571429  1.420000  0.000000   
2019-03-23 22:00:00    1.307692  1.881538   8.923077  1.094615  0.000000   
2019-03-23 23:00:00    1.615385  3.725385  15.115385  1.696154  0.000000   

                         total  
pickup_time                     
2019-03-23 00:00:00  12.965000  
2019-03-23 01:00:00  12.575000  
2019-03-23 02:00:00  13.169091  
2019-03-23 03:00:00  17.335000  
2019-03-23 04:00:00  10.215000  
2019-03-23 05:00:00  10.530000  
2019-03-23 06:00:00  23.133333  
2019-03-23 07:00:00   9.298333  
2019-03-23 08:00:00   3.300000  
2019-03-23 09:00:00  12.124000  
2019-03-23 10:00:00  12.152500  
2019-03-23 11:00:00  14.667273  
2019-03-23 12:00:00  13.420000  
2019-03-23 13:00:00  12.344000  
2019-03-23 14:00:00  24.267059  
2019-03-23 15:00:00  30.370000  
2019-03-23 16:00:00  14.431818  
2019-03-23 17:00:00  20.739091  
2019-03-23 18:00:00  16.427143  
2019-03-23 19:00:00  14.226316  
2019-03-23 20:00:00  15.944000  
2019-03-23 21:00:00  15.791429  
2019-03-23 22:00:00  13.433077  
2019-03-23 23:00:00  20.034615

Check https://colab.research.google.com/github/CodeSolid/CodeSolid.github.io/blob/main/booksource/exercises/PandasExercises.ipynb for more Pandas exercises.